// SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
// SPDX-FileCopyrightText: 2024 gluesniffler <159397573+gluesniffler@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Humanity.Visuals;
using Content.Shared._Shitmed.Targeting;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Shitmed.UserInterface.Systems.Targeting.Widgets;

[GenerateTypedNameReferences]
public sealed partial class TargetingControl : UIWidget
{
    private static readonly StyleBoxFlat HoverHighlight = new()
    {
        BackgroundColor = Color.FromHex("#FFE08A40"),
        BorderColor = Color.FromHex("#FFE08A"),
        BorderThickness = new Thickness(2),
    };
    private static readonly StyleBoxFlat SelectedHighlight = new()
    {
        BackgroundColor = Color.FromHex("#FF776030"),
        BorderColor = Color.FromHex("#FF7760"),
        BorderThickness = new Thickness(1),
    };
    private readonly TargetingUIController _controller;
    private readonly Dictionary<TargetBodyPart, TextureButton> _bodyPartControls;
    private TargetBodyPart? _activeBodyPart;
    private TargetBodyPart? _hoveredBodyPart;

    public TargetingControl()
    {
        RobustXamlLoader.Load(this);
        _controller = UserInterfaceManager.GetUIController<TargetingUIController>();

        _bodyPartControls = new Dictionary<TargetBodyPart, TextureButton>
        {
            // TODO: ADD EYE AND MOUTH TARGETING
            { TargetBodyPart.Head, HeadButton },
            { TargetBodyPart.Torso, ChestButton },
            { TargetBodyPart.Groin, GroinButton },
            { TargetBodyPart.LeftArm, LeftArmButton },
            { TargetBodyPart.LeftHand, LeftHandButton },
            { TargetBodyPart.RightArm, RightArmButton },
            { TargetBodyPart.RightHand, RightHandButton },
            { TargetBodyPart.LeftLeg, LeftLegButton },
            { TargetBodyPart.LeftFoot, LeftFootButton },
            { TargetBodyPart.RightLeg, RightLegButton },
            { TargetBodyPart.RightFoot, RightFootButton },
        };

        foreach (var bodyPartButton in _bodyPartControls)
        {
            bodyPartButton.Value.MouseFilter = MouseFilterMode.Stop;
            bodyPartButton.Value.OnPressed += _ => SetActiveBodyPart(bodyPartButton.Key);
            bodyPartButton.Value.OnMouseEntered += _ =>
            {
                _hoveredBodyPart = bodyPartButton.Key;
                UpdateHighlights();
            };
            bodyPartButton.Value.OnMouseExited += _ =>
            {
                if (_hoveredBodyPart == bodyPartButton.Key)
                    _hoveredBodyPart = null;
                UpdateHighlights();
            };
        }
        UpdateDoll();
        AddChild(new TargetingHighlights(this)
        {
            HorizontalExpand = true,
            VerticalExpand = true,
            MouseFilter = MouseFilterMode.Ignore,
        });
    }

    private void SetActiveBodyPart(TargetBodyPart bodyPart) => _controller.CycleTarget(bodyPart);

    public void SetBodyPartsVisible(TargetBodyPart bodyPart)
    {
        _activeBodyPart = bodyPart;
        UpdateHighlights();
    }

    private void UpdateHighlights()
    {
        foreach (var bodyPartButton in _bodyPartControls)
        {
            var overlay = (TextureRect) bodyPartButton.Value.GetChild(0);
            var selected = bodyPartButton.Key == _activeBodyPart;
            var hovered = bodyPartButton.Key == _hoveredBodyPart;
            overlay.Visible = selected || hovered;
            overlay.ModulateSelfOverride = hovered
                ? Color.FromHex("#FFE08A")
                : Color.FromHex("#FF7760");
        }
    }

    private void UpdateDoll()
    {
        var texture = Theme.ResolveTexture("target_doll");
        TargetDoll.Texture = texture;
        HumanityTargetingLayout.Apply(texture, _bodyPartControls);
        UpdateHighlights();
    }

    private sealed class TargetingHighlights(TargetingControl owner) : Control
    {
        protected override void Draw(DrawingHandleScreen handle)
        {
            base.Draw(handle);
            foreach (var (part, button) in owner._bodyPartControls)
            {
                if (part != owner._hoveredBodyPart && part != owner._activeBodyPart)
                    continue;

                var bounds = UIBox2.FromDimensions(button.GlobalPixelPosition - GlobalPixelPosition, button.PixelSize);
                var highlight = part == owner._hoveredBodyPart ? HoverHighlight : SelectedHighlight;
                highlight.Draw(handle, bounds, UIScale);
            }
        }
    }

    protected override void OnThemeUpdated() => UpdateDoll();

    public void SetTargetDollVisible(bool visible) => Visible = visible;

}
