# German
- type: job
  id: GulagPrisonerGerman
  name: job-name-civ-gulag-prisoner-german
  icon: JobIconHumanityGulagPrisonerGerman
  faction: GulagPrisonerGerman
  originalName: Немецкий заключённый
  description: job-description-civ-gulag-prisoner
  startingGear: GulagPrisonerGear
  playTimeTracker: JobGulagPrisonerGerman
  special:
    - !type:AddComponentSpecial
      components:
        - type: NpcFactionMember
          factions:
            - GulagPrisonerGerman
        - type: ShowFactionIcons
          factionIcon: Ger3Faction

# Ukrainian
- type: job
  id: GulagPrisonerUkrainian
  name: job-name-civ-gulag-prisoner-ukrainian
  icon: JobIconHumanityGulagPrisonerUkrainian
  faction: GulagPrisonerUkrainian
  originalName: Украинский заключённый
  description: job-description-civ-gulag-prisoner
  startingGear: GulagPrisonerGear
  playTimeTracker: JobGulagPrisonerUkrainian
  special:
    - !type:AddComponentSpecial
      components:
        - type: NpcFactionMember
          factions:
            - GulagPrisonerUkrainian
        - type: ShowFactionIcons
          factionIcon: UkrFaction

# Polish
- type: job
  id: GulagPrisonerPolish
  name: job-name-civ-gulag-prisoner-polish
  icon: JobIconHumanityGulagPrisonerPolish
  faction: GulagPrisonerPolish
  originalName: Польский заключённый
  description: job-description-civ-gulag-prisoner
  startingGear: GulagPrisonerGear
  playTimeTracker: JobGulagPrisonerPolish
  special:
    - !type:AddComponentSpecial
      components:
        - type: NpcFactionMember
          factions:
            - GulagPrisonerPolish
        - type: ShowFactionIcons
          factionIcon: PolFaction

# Starting gear
- type: startingGear
  id: GulagPrisonerGear
  equipment:
    shoes: ClothingShoesColorBlack # this should be changed since they look silly
    jumpsuit: civ13_uniform_GULAG_prisoner_clothing
    pocket2: Roubles
