- type: rank
  id: RankSergeantMajor
  name: Сержант-майор
  prefix: Серж.-майор
  paygrade: E9

- type: rank
  id: RankFirstSergeant
  name: Первый сержант
  prefix: 1-й серж.
  paygrade: E8

- type: rank
  id: RankMasterSergeant
  name: Мастер-сержант
  prefix: Мастер-серж.
  paygrade: E7

- type: rank
  id: RankStaffSergeant
  name: Штаб-сержант
  prefix: Штаб-серж.
  paygrade: E6

- type: rank
  id: RankSergeant
  name: Сержант
  prefix: Серж.
  paygrade: E5

- type: rank
  id: RankCorporal
  name: Капрал
  prefix: Капр.
  paygrade: E4

- type: rank
  id: RankLanceCorporal
  name: Младший капрал
  prefix: Мл. капр.
  paygrade: E3

- type: rank
  id: RankPrivateFirstClass
  name: Рядовой первого класса
  prefix: Ряд. 1-го кл.
  paygrade: E2

- type: rank
  id: RankPrivate
  name: Рядовой
  prefix: Ряд.
  paygrade: E1
