- type: rank
  id: RankFieldMarshal
  name: Фельдмаршал
  prefix: Фельдм.
  paygrade: O11

- type: rank
  id: RankGeneral
  name: Генерал
  prefix: Ген.
  paygrade: O10

- type: rank
  id: RankLieutenantGeneral
  name: Генерал-лейтенант
  prefix: Ген.-лейт.
  paygrade: O9

- type: rank
  id: RankMajorGeneral
  name: Генерал-майор
  prefix: Ген.-майор
  paygrade: O8

- type: rank
  id: RankBrigadierGeneral
  name: Бригадный генерал
  prefix: Бриг. ген.
  paygrade: O7

- type: rank
  id: RankColonel
  name: Полковник
  prefix: Полк.
  paygrade: O6

- type: rank
  id: RankLieutenantColonel
  name: Подполковник
  prefix: Подполк.
  paygrade: O5

- type: rank
  id: RankMajor
  name: Майор
  prefix: Майор
  paygrade: O4

- type: rank
  id: RankCaptain
  name: Капитан
  prefix: Кап.
  paygrade: O3

- type: rank
  id: RankFirstLT
  name: Старший лейтенант
  prefix: Ст. лейт.
  paygrade: O2

- type: rank
  id: RankSecondLT
  name: Младший лейтенант
  prefix: Мл. лейт.
  paygrade: O1
