using Content.Client.Humanity.Mortar;
using Content.Shared._RMC14.Mortar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Mortar;

[GenerateTypedNameReferences]
public sealed partial class MortarWindow : DefaultWindow
{
    private readonly MortarDialSpinBox _heading = new();
    private readonly MortarDialSpinBox _range = new();
    private int _minimum;
    private int _maximum;
    public event Action<float, int>? AimChanged;

    public MortarWindow()
    {
        RobustXamlLoader.Load(this);
        HeadingContainer.AddChild(_heading);
        RangeContainer.AddChild(_range);
        _heading.Changed += _ => ApplyAim();
        _range.Changed += _ => ApplyAim();
        LeftCoarse.OnPressed += _ => ChangeHeading(-15);
        RightCoarse.OnPressed += _ => ChangeHeading(15);
        NearCoarse.OnPressed += _ => ChangeRange(-10);
        FarCoarse.OnPressed += _ => ChangeRange(10);
    }

    private void ChangeHeading(int amount)
    {
        _heading.Value += amount;
        ApplyAim();
    }

    private void ChangeRange(int amount)
    {
        _range.Value += amount;
        ApplyAim();
    }

    private void ApplyAim()
    {
        if (!float.IsFinite(_heading.Value) || !float.IsFinite(_range.Value))
            return;
        _heading.Value = (_heading.Value % 360 + 360) % 360;
        _range.Value = Math.Clamp(_range.Value, _minimum, _maximum);
        AimChanged?.Invoke(_heading.Value, (int) _range.Value);
    }

    public void Refresh(MortarComponent mortar)
    {
        _minimum = mortar.MinimumRange;
        _maximum = mortar.MaximumRange;
        _heading.Value = mortar.Heading;
        _range.Value = mortar.Range;
        StatusLabel.Text = Loc.GetString(mortar.Loaded ? "humanity-mortar-ready" : "humanity-mortar-empty");
        FireButton.Disabled = !mortar.Loaded || !mortar.Deployed;
    }
}
