# Welcome to the example configuration file!
# Remember that if this is in bin/Content.Server or such, it may be overwritten on build.
# Consider copying it and using the --config-file and --data-dir options.

[log]
path = "logs"
format = "log_%(date)s-%(time)s.txt"
level = 2
enabled = true

[net]
tickrate = 20
port = 1212
bindto = "::,0.0.0.0"
max_connections = 256

[status]
enabled = true

[game]
hostname = "Humanity"
lobbyenabled = true
desc = "Humanity — Кочевники и Вторая мировая: развитие цивилизации или бой Германии против СССР."
maxplayers = 256
lobbyduration = 60
disallowlatejoins = false
defaultpreset = "ww2"
fallbackpreset = "TDMWW2"
usepersistence = false
map = ""
map_pool = "HumanityWorldWarTwoMaps"
map_rotation = false

[config]
preset_debug = false
preset_development = false

[vote]
preset_enabled = true
map_enabled = false

[viewport]
maximum_width = 64

[console]
loginlocal = true
login_host_user = ""

[hub]
# Set to true to show this server on the public server list
# Before enabling this, read: https://docs.spacestation14.io/hosts/hub-rules
advertise = false
# Comma-separated list of tags, useful for categorizing your server.
# See https://docs.spacestation14.io/hosts/hub-rules for more details on this when it becomes relevant.
tags = "region:eu_w,rp:med"
# URL of your server. Fill this in if you have a domain name,
# want to use HTTPS (with a reverse proxy), or other advanced scenarios.
# Must be in the form of an ss14:// or ss14s:// URI pointing to the status API.
server_url = ""
# Comma-separated list of URLs of hub servers to advertise to.
hub_urls = "https://hub.spacestation14.com/"

[auth]
# Authentication (accounts):
# 0 = Optional, 1 = Required, 2 = Disabled
# Presumably do require authentication on any public server.
mode = 1
# If true, even if authentication is required, localhost is still allowed to login directly regardless.
allowlocal = false

[database]
# Database type to use. Can be "sqlite" or "postgres" currently.
engine = "sqlite"

# Path to store the database at when using SQLite. Note that is NOT a disk path.
# This is relative to the server data directory, which is specified by --data-dir when starting the server from the command (or automatically set by SS14.Watchdog)
sqlite_dbpath = "preferences.db"

# PostgreSQL database configuration, should be self explanatory.
pg_host = "localhost"
pg_port = 5432
pg_database = "ss14"
pg_username = ""
pg_password = ""

[infolinks]

[server]
lobby_right_panel_width = 500
