name: Map file schema validator
on:
  push:
    branches: [ master, staging, stable ]
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  yaml-schema-validation:
    name: YAML map schema validator
    if: github.actor != 'PJBot' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
    - name: Setup Submodule
      run: git submodule update --init --recursive
    - uses: PaulRitter/yaml-schema-validator@v1
      with:
        schema: RobustToolbox/Schemas/mapfile.yml
        path_pattern: .*Resources/Maps/.*
        validators_path: RobustToolbox/Schemas/mapfile_validators.py
        validators_requirements: RobustToolbox/Schemas/mapfile_requirements.txt
